# tekartik flutter recommended lints (extension over google lints and pedantic)
include: package:tekartik_app_lints_flutter/recommended.yaml

analyzer:
  exclude:
    - lib/generated_plugin_registrant.dart