name: flutter_app_example_repo_support
publish_to: none
deploy_to: none

environment:
  sdk: ^3.4.0

dependencies:
  process_run:
  path:
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
    version: '>=0.7.8'

dev_dependencies:
  test: '>=1.0.0'
  dev_build: '>=0.13.4-dev.1'

dependency_overrides:
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
