name: flutter_app_example_repo_support
publish_to: none
deploy_to: none

environment:
  sdk: ^3.8.0

dependencies:
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
  tekartik_build_utils:
    git:
      url: https://github.com/tekartik/build_utils.dart
      ref: dart3a
    version: '>=0.7.8'

dev_dependencies:
  test: ">=1.24.0"
  dev_build: ">=1.1.2"

dependency_overrides:
resolution: workspace
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
