name: Run CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            flutter: stable
          - os: ubuntu-latest
            flutter: beta
          - os: windows-latest
            flutter: stable
          - os: macos-latest
            flutter: stable

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter }}
      - run: dart --version
        # Setup sqlite3 lib (done for linux only but works safely on all platform)
      - name: Install libsqlite3-dev
        run: |
          dart pub global activate --source git https://github.com/tekartik/ci.dart --git-path ci
          dart pub global run tekartik_ci:setup_sqlite3lib
      - run: flutter --version
      - run: flutter upgrade
      - run: dart pub global activate dev_build
      - run: dart pub global run dev_build:run_ci --recursive
