name: Run CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: repo_support
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            flutter: stable
          - os: ubuntu-latest
            flutter: beta
          - os: windows-latest
            flutter: stable
          - os: macos-latest
            flutter: stable

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter }}
      - run: dart --version
      - run: flutter --version
      - run: flutter upgrade
      - run: dart pub get
      - run: dart run tool/run_ci.dart